# Generated by Django 3.2.20 on 2024-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240322_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='name',
            field=models.CharField(help_text='รายละเอียด', max_length=250, verbose_name='Description'),
        ),
    ]
